name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupJDK21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Install xvfb for GUI tests
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run tests with virtual display and timeout
        run: |
          timeout 120s xvfb-run -a sbt test || {
            echo "Tests timed out, killing remaining processes"
            pkill -f sbt || true
            pkill -f java || true
            exit 1
          }